### PR TITLE
feat: declare compatibility with mocha@7

### PR DESCRIPTION
**Pull request by AviVahl**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case
- testing loader with the new mocha version.
- added new version to peerDependencies.
- upgrade all deps to latest stable (and regenerated lock file).

### Breaking Changes

None.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Release will be tomorrow

**Comment by AviVahl** [comment]
@evilebottnawi kind reminder about that release. I want to upgrade several repositories to mocha@7 and awaiting it... :)

**Comment by evilebottnawi** [comment]
@AviVahl sorry for delay, I broke my finger and there were problems, already working on a release

**Comment by AviVahl** [comment]
Sorry to hear. I wish you well and quick recovery. 🙏

**Pull request merged**
