### PR TITLE
fix: remove broken handling of "target": "node"

### LINKED ISSUE #89: TS2307: Cannot find module node_modules/mocha-loader/dist/EnhancedMocha.js
- Operating System: macOS Catalina
- Node Version: v10.15.2
- NPM Version: 6.4.1, we're using Yarn 1.15.2
- webpack Version: 4.41.6
- mocha-loader Version: 4.0.1

### Expected Behavior

Tests run as a part of the webpack

### Actual Behavior

Getting a compilation error, tests don't run in webpack but run using the standalone mocha binary

### Code

```js
// webpack.config.js
const slsw = require('serverless-webpack');
module.exports = {
  mode,
  entry: slsw.lib.entries,
  resolve: {
    plugins: [new TsconfigPathsPlugin()],
    extensions: [
      '.js',
      '.ts',
    ]
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  stats: {
    modules: true,
    colors: false,
  },
  target: 'node',
  module: {
    rules: [{
      test: /\.ts$/,
      use: [{
        loader: 'ts-loader'
      }],
    }, {
      test: /test\.ts$/,
      use: [{
        loader: 'mocha-loader'
      }],
      exclude: /node_modules/,
    }]
  },
  plugins: [
    new ProgressPlugin({profile: false}),
  ],
};
```

### How Do We Reproduce?

Create a new project with serverless, serverless-webpack and mocha-loaded with the tests written in Typescript. Run `sls package`, see the error.

### PR DESCRIPTION
**Pull request by AviVahl**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
This flow was never covered by any tests and got broken by mocha itself, as it's no longer bundle-compatible when targeting node.

Closes #89 by now throwing an error about an unsupported target.

Should be noted that test files can always be bundled without mocha-loader. The resulting bundle can later be executed in node using the mocha cli.

### Breaking Changes
Replaced bundling errors with a proper "unsupported target" error. Not sure whether it's considered breaking to remove something that doesn't work anyway.

### CODE REVIEW

**Comment by AviVahl** [comment]
Yeah, a major version. Just to be on the safe side...
I'll rebase branch to current `master`.

**Comment by evilebottnawi** [comment]
@AviVahl Do we need to implement anything else before releasing the major version?

**Comment by AviVahl** [comment]
not really. go ahead. :+1:

**Comment by evilebottnawi** [comment]
Thanks!

**Pull request merged**
