### PR TITLE
chore(deps): style-loader@2.0.0

### PR DESCRIPTION
**Pull request by AviVahl**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**
- [x] **dependency update**

### Motivation / Use-Case

Use the newly-released `style-loader@2.0.0`.

### Breaking Changes

None

### Additional Info
Can be released as a patch version

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
It can be breaking change, because now you need to use `import` or `require().default`

**Comment by AviVahl** [comment]
That loader is currently used as:
`source.push(`require(${stringify(`!!style-loader!css-loader!${mochaCss}`)});`);`
And I checked it manually as well. Mocha's css loads as expected.

Since it is only used internally (to load `mocha.css`), I wouldn't consider this a breaking change. No user-facing changes (for users of `mocha-loader` itself).

**Comment by evilebottnawi** [comment]
I think you need `source.push(`require(${stringify(`!!style-loader!css-loader!${mochaCss}`)}).default;`);` now

**Comment by AviVahl** [comment]
> I think you need `source.push(`require(${stringify(`!!style-loader!css-loader!${mochaCss}`)}).default;`);` now

I would if the exported value was actually used (saved into a variable, for example). But here it's used as a side-effect require() to load a `<style />`-element with mocha's css.

**Comment by evilebottnawi** [comment]
Just use `import` :smile: but maybe it is work, need add test(s) on this

**Comment by AviVahl** [comment]
I actually tried that in the past and reverted back to require calls... there were subtle behavioral changes between the two, in terms of timing and order. The require call seemed to work ideally, so I left it. If I remember correctly, there was a tiny load-time style-jump when page initially loaded when `import '!!style-loader!css-loader!${mochaCss}';` was used.

**Comment by evilebottnawi** [comment]
Maybe you can test it manually?

**Comment by AviVahl** [comment]
I checked it again. Here's the deal:

`import '...${mochaCss}';` works just fine... just like the `require` call... styles load, and I could leave it like that.

But there are other require calls generated in the pitch module... and they break if I convert them to `import`s (caught in test: `describe is not defined`).

`import` statements are hoisted, I think, which causes the generated `.setup()` call to not occur before the evaluation of the test file.

Now, that module is currently pure commonjs. having it as pure esm fails... do we want to generate a mixed module? I would personally leave it as-is. WDYT?

**Comment by evilebottnawi** [comment]
We can use inline syntax `!!style-loader?esModule=false!css-loader!${mochaCss}`

**Comment by AviVahl** [comment]
I'm not referring to the module `style-loader` creates. I'm referring to the module `mocha-loader` creates. It is pure commonjs right now. I would rather not change it to be a mixed import and require calls.

What benefit would `esModule: false` on the style loader give? It's ok for style-loader to generate either esm or commonjs, as both work for this use case.

**Comment by evilebottnawi** [comment]
What benefit would esModule: false on the style loader give? 

Only using `import` instead `require`

**Comment by AviVahl** [comment]
I think there's some confusion here. I'll try to clarify.

`mocha-loader` currently generates:
```
require([mocha's css]);
var mochaModule = require([mocha's js]);
var mochaInstance = window.mocha || mochaModule; // so it works with newer mocha and older mocha
mochaInstance.setup(...)
require([test file]);
require([start script]); 
```
Now, the first require call (`require([mocha's css]);`) ensures mocha's css will load into a style element. It uses `style-loader` and `css-loader` to do so.

I can change the code today to say:
```
import [mocha's css];
var mochaModule = require([mocha's js]);
var mochaInstance = window.mocha || mochaModule; // so it works with newer mocha and older mocha
mochaInstance.setup(...)
require([test file]);
require([start script]); 
```
And the style still loads. All is good. It doesn't matter if it's `style-loader@1` or `style-loader@2`. It doesn't matter if `style-loader` generates esm or commonjs for its own module.

The issue? the above module is hybrid. It mixes both an `import` statement and several `require` calls.

So the next step would be to:
```
import [mocha's css];
import mochaModule from [mocha's js];
var mochaInstance = window.mocha || mochaModule; // so it works with newer mocha and older mocha
mochaInstance.setup(...)
import [test file];
import [start script]; 
```
The above is a pure-esm module, as it only uses `import` statements. It doesn't work. It fails the e2e saying `describe is not defined`. I'm guessing it happens because `import [test file];` starts evaluating before the `mochaInstance.setup(...)` call evaluates.

My suggestion? Leave the PR as-is (pure-commonjs). Everything works as expected.
If we want to consider migrating to pure esm modules, that should occur in a different PR, and we should somehow resolve the evaluation order.

I hope this clarifies things a bit.

**Review by evilebottnawi — APPROVED** [review]

**Comment by evilebottnawi** [comment]
Should we do release?

**Comment by AviVahl** [comment]
Yes, with this included. It can be a patch release, as we already dropped those Node versions, and consumer behavior isn't changed.

**Pull request merged**
