### PR TITLE
ci: migrate on github actions

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

migrate on github actions + update deps + polyfill for `events.once` for old node versions

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Comment by AviVahl** [comment]
Will try to get to it this weekend... Best guess: maybe the no-longer-needed `pipe: true`.

**Comment by AviVahl** [comment]
@evilebottnawi everything appears to pass now, post the upgrades on `master`. I've disabled the audit and the only thing that failed is my commit message inside the branch. feel free to squash it to master.

You may have to adjust the protected branch settings in github, so it requires actions to pass instead of azure.

**Comment by evilebottnawi** [comment]
@AviVahl Thanks, I will do it tomorrow :+1:

**Pull request merged**
