### PR TITLE
Mark mocha@6 compatibility and upgrade all dependencies

### PR DESCRIPTION
**Pull request by AviVahl**
- fixed lint warnings in EnhancedMocha.js
- updated bundle snapshot
- switched to `@webpack-contrib/defaults`

This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**
- [x] deps upgrade (not in template)
### Motivation / Use-Case

css-loader@2 came out and uses postcss@7.

### Breaking Changes

`css-loader` has breaking changes, but it is only used to load `mocha`'s css here, so nothing breaking is expected.

### CODE REVIEW

**Comment by AviVahl** [comment]
@michael-ciniawsky, any chance you could check this out? :)

**Comment by AviVahl** [comment]
Upgraded to css-loader@2.0.1.

any chance someone reviews this? perhaps @evilebottnawi?

**Comment by AviVahl** [comment]
Someone? Anyone?
This is the only reason all our projects have `postcss@6` next to `postcss@7`.

**Comment by AviVahl** [comment]
Updated dependencies once more. Would be awesome if this could be reviewed/merged/released.

**Comment by AviVahl** [comment]
@TheLarkInn heya! any idea who do I need to mention for this to get reviewed? :)

**Comment by AviVahl** [comment]
@evilebottnawi thx for reviewing. any chance to get a release with these dep upgrades?

**Comment by AviVahl** [comment]
This is frustrating. :disappointed:

**Comment by AviVahl** [comment]
Ping?

**Comment by tomrav** [comment]
Any chance this could merged? It's causing a lot of un-needed dependencies down the line.

**Comment by evilebottnawi** [comment]
Currently we have no active maintainers for this project. if somebody want to help us with `mocha-loader` please ping me and we connect in slack about future and roadmap

**Comment by AviVahl** [comment]
Both I and @tomrav are willing to keep this one maintained.
We work together at `Wix.com` and care about keeping this one working.

**Comment by evilebottnawi** [comment]
@AviVahl do you have right on merge and release?

**Comment by AviVahl** [comment]
Not sure what you mean.
I have my github user ([AviVahl](https://github.com/AviVahl)) and npm user ([avi.vahl](https://www.npmjs.com/~avi.vahl)).
Both are setup using two factor authentication.
I have no existing permissions to any project in the `webpack`/`webpack-contrib` organizations.

**Comment by evilebottnawi** [comment]
@AviVahl send invite, please ping me when you accept

**Comment by AviVahl** [comment]
Awesome. Accepted.
Do you guys use continuous or manual deployment to npm?

**Comment by evilebottnawi** [comment]
@AviVahl manual right now, i need you @tomrav npm nickname

@AviVahl Right now do you have ability to merge, right?

**Comment by hiroppy** [comment]
I can help too:)

**Comment by AviVahl** [comment]
I do. Thanks.
I want to get the lock file up to date again before merging this PR.
Will also add `mocha@6` to peer deps

My npm user: avi.vahl
Tom's npm user: tomrav

**Comment by evilebottnawi** [comment]
@AviVahl Can't add to npm (they still can't fix bug around adding users - `user tomrav not found.`, problem exists around 9 mouth), looks we need to me for release, https://npm.community/t/cant-add-collaborators-using-site-and-cli/3546

**Comment by evilebottnawi** [comment]
Just ping me when all will be done

**Comment by AviVahl** [comment]
Updated all `devDeps` again. Also marked as compatible with `mocha@6`.
@tomrav can you review?

**Comment by tomrav** [comment]
Looks good to me. 👍

**Comment by AviVahl** [comment]
@evilebottnawi squashed to master. (accidentally omitted the `#76` link in the commit title; sorry)
can you release a new patch version? :)

**Comment by evilebottnawi** [comment]
:+1:

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack-contrib/mocha-loader/releases/tag/v2.0.1

**Pull request merged**
