### PR TITLE
chore(deps): loader-utils@2, latest others

### PR DESCRIPTION
**Pull request by AviVahl**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**
- [x] **dependency upgrades**.

### Motivation / Use-Case
Ensure users always get latest bug fixes and that package is properly deduped.
 
### Breaking Changes
Non that I'm aware of, as this package is already Node 10+.

### CODE REVIEW

**Comment by AviVahl** [comment]
@evilebottnawi Thanks for the review.

Lint currently fails in CI, as it runs `npm audit`. The versions are as up-to-date as they can be given our dependencies. Most audit failures are around older versions of `mkdirp` bringing even older (pinned) `minimist`. Many packages in the ecosystem use `mkdirp`, so the number of vulnerabilities multiplied.

**current master**: `found 3255 moderate severity vulnerabilities in 1217640 scanned packages`
**this PR**: `found 1514 moderate severity vulnerabilities in 1217966 scanned packages`

There's a decrease, but until everyone upgrades their packages, there's not much we can do.
The CI feels overly strict, as it can start failing without anything changing in the project at all.

**Comment by evilebottnawi** [comment]
Let's ignore it, can we merge it, do we need release?

**Comment by AviVahl** [comment]
Yeah, it's ready to merge and can be released as a patch release. Thanks.

**Comment by evilebottnawi** [comment]
Done :+1:

**Pull request merged**
